steps:
  - id: "Build and push image"
    name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --dockerfile=${_DOCKERFILE}
      - --destination=asia.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}
      - --cache=true
      - --build-arg=SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}

  - id: "deploy service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_DEPLOY_REGION}",
        "--image",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}",
        "--tag",
        "pr-${_PR_NUMBER}",
        "--no-traffic",
      ]

options:
  machineType: "E2_HIGHCPU_8"
